responsive for desktop
Abhinav-ark/Amrita_map pull request #4
Opened 2024-09-30 12:13 UTC by thecodingvivek

2024-10-01 17:23 UTC, Abhinav-ark requested changes
## Navigator is not displaying next destination in mobile view.
https://github.com/user-attachments/assets/ebb1c055-0323-4966-a6d0-74c6822ab603

The navigator which shows directions, next destination and distance is not displaying the later in mobile view.

2024-10-01 17:23 UTC, Abhinav-ark commented on index.html
> +                <a class="navbaractive" onclick="setTimeout(()=> {closenav()},200);">Map <span class="material-symbols-outlined leftmargin5">map</span></a>
Why do we need a delay here?

2024-10-01 17:23 UTC, Abhinav-ark commented on index.html
> +                <a class="navbaractive" onclick="setTimeout(()=> {closenav()},200);">Map <span class="material-symbols-outlined leftmargin5">map</span></a>
The delay ensures that the hamburger animation and hiding of the navbar are synchronized with each other.

2024-10-03 16:50 UTC, Abhinav-ark approved these changes
Good For Now.

2024-10-03 16:50 UTC, ROHITH-M10 approved these changes
LGTM.

2024-10-03 16:51 UTC, merged